# config.yml

backend:
  name: github # Or gitlab
  repo: martijnvdbrug/vandebrughoveniers.nl # Your username and repository
  branch: master # Branch to use
  base_url: https://europe-west1-cable-cms.cloudfunctions.net/authHandler # The base URL for your Firebase Function
  auth_endpoint: /auth # The path to the OAuth endpoint of the function

media_folder: 'images/uploads'
collections:
  - label: "Pagina's"
    name: "pages"
    delete: false
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Content, name: content, widget: text}
  - name: 'portfolio'
    label: 'Portfolio'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
