# config.yml

backend:
  name: github # Or gitlab
  repo: martijnvdbrug/vandebrughoveniers.nl # Your username and repository
  branch: master # Branch to use
  base_url: https://europe-west1-cable-cms.cloudfunctions.net/authHandler # The base URL for your Firebase Function
  auth_endpoint: /auth # The path to the OAuth endpoint of the function

media_folder: 'images/uploads'
collections:
  - label: "Pagina's"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "_data/home.yml"
        fields:
          - {label: Titel, name: title, widget: string}
          - {label: Content, name: content, widget: text}